services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILDKIT_INLINE_CACHE: 1
    volumes:
      - vscode-gradle-volume:/home/vscode/.gradle
      - vscode-m2-volume:/home/vscode/.m2
    privileged: true
    command: sleep infinity

volumes:
  vscode-gradle-volume:
  vscode-m2-volume:
